//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICUPatientMonitorModuleLib.AlertWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BedData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BedData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BedAvailabilityField;
        
        private int BedIDField;
        
        private int PatientIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool BedAvailability {
            get {
                return this.BedAvailabilityField;
            }
            set {
                if ((this.BedAvailabilityField.Equals(value) != true)) {
                    this.BedAvailabilityField = value;
                    this.RaisePropertyChanged("BedAvailability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BedID {
            get {
                return this.BedIDField;
            }
            set {
                if ((this.BedIDField.Equals(value) != true)) {
                    this.BedIDField = value;
                    this.RaisePropertyChanged("BedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PatientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PatientPulseRateField;
        
        private decimal PatientSpo2Field;
        
        private double PatientTempratureField;
        
        private int PatientIDField;
        
        private int BedIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PatientPulseRate {
            get {
                return this.PatientPulseRateField;
            }
            set {
                if ((this.PatientPulseRateField.Equals(value) != true)) {
                    this.PatientPulseRateField = value;
                    this.RaisePropertyChanged("PatientPulseRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PatientSpo2 {
            get {
                return this.PatientSpo2Field;
            }
            set {
                if ((this.PatientSpo2Field.Equals(value) != true)) {
                    this.PatientSpo2Field = value;
                    this.RaisePropertyChanged("PatientSpo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double PatientTemprature {
            get {
                return this.PatientTempratureField;
            }
            set {
                if ((this.PatientTempratureField.Equals(value) != true)) {
                    this.PatientTempratureField = value;
                    this.RaisePropertyChanged("PatientTemprature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((this.PatientIDField.Equals(value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int BedID {
            get {
                return this.BedIDField;
            }
            set {
                if ((this.BedIDField.Equals(value) != true)) {
                    this.BedIDField = value;
                    this.RaisePropertyChanged("BedID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertFinalListStructure", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AlertFinalListStructure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int bedIDField;
        
        private bool healthyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int bedID {
            get {
                return this.bedIDField;
            }
            set {
                if ((this.bedIDField.Equals(value) != true)) {
                    this.bedIDField = value;
                    this.RaisePropertyChanged("bedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool healthy {
            get {
                return this.healthyField;
            }
            set {
                if ((this.healthyField.Equals(value) != true)) {
                    this.healthyField = value;
                    this.RaisePropertyChanged("healthy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlertWebServiceReference.ICUPatientAlertServiceSoap")]
    public interface ICUPatientAlertServiceSoap {
        
        // CODEGEN: Generating message contract since element name ConfigureBedsWebMethodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfigureBedsWebMethod", ReplyAction="*")]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse ConfigureBedsWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfigureBedsWebMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse> ConfigureBedsWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest request);
        
        // CODEGEN: Generating message contract since element name AllocateBedsWebMethodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocateBedsWebMethod", ReplyAction="*")]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse AllocateBedsWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllocateBedsWebMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse> AllocateBedsWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest request);
        
        // CODEGEN: Generating message contract since element name DischargePatientWebMethodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DischargePatientWebMethod", ReplyAction="*")]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse DischargePatientWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DischargePatientWebMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse> DischargePatientWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest request);
        
        // CODEGEN: Generating message contract since element name RingAlarmWebMethodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RingAlarmWebMethod", ReplyAction="*")]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse RingAlarmWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RingAlarmWebMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse> RingAlarmWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest request);
        
        // CODEGEN: Generating message contract since element name PatientDataWebMethodResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientDataWebMethod", ReplyAction="*")]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse PatientDataWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientDataWebMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse> PatientDataWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfigureBedsWebMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfigureBedsWebMethod", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequestBody Body;
        
        public ConfigureBedsWebMethodRequest() {
        }
        
        public ConfigureBedsWebMethodRequest(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigureBedsWebMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int numOfBeds;
        
        public ConfigureBedsWebMethodRequestBody() {
        }
        
        public ConfigureBedsWebMethodRequestBody(int numOfBeds) {
            this.numOfBeds = numOfBeds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfigureBedsWebMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfigureBedsWebMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponseBody Body;
        
        public ConfigureBedsWebMethodResponse() {
        }
        
        public ConfigureBedsWebMethodResponse(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfigureBedsWebMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.BedData[] ConfigureBedsWebMethodResult;
        
        public ConfigureBedsWebMethodResponseBody() {
        }
        
        public ConfigureBedsWebMethodResponseBody(ICUPatientMonitorModuleLib.AlertWebServiceReference.BedData[] ConfigureBedsWebMethodResult) {
            this.ConfigureBedsWebMethodResult = ConfigureBedsWebMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllocateBedsWebMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllocateBedsWebMethod", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequestBody Body;
        
        public AllocateBedsWebMethodRequest() {
        }
        
        public AllocateBedsWebMethodRequest(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllocateBedsWebMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int patientID;
        
        public AllocateBedsWebMethodRequestBody() {
        }
        
        public AllocateBedsWebMethodRequestBody(int patientID) {
            this.patientID = patientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllocateBedsWebMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllocateBedsWebMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponseBody Body;
        
        public AllocateBedsWebMethodResponse() {
        }
        
        public AllocateBedsWebMethodResponse(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllocateBedsWebMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] AllocateBedsWebMethodResult;
        
        public AllocateBedsWebMethodResponseBody() {
        }
        
        public AllocateBedsWebMethodResponseBody(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] AllocateBedsWebMethodResult) {
            this.AllocateBedsWebMethodResult = AllocateBedsWebMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DischargePatientWebMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DischargePatientWebMethod", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequestBody Body;
        
        public DischargePatientWebMethodRequest() {
        }
        
        public DischargePatientWebMethodRequest(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DischargePatientWebMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int patientID;
        
        public DischargePatientWebMethodRequestBody() {
        }
        
        public DischargePatientWebMethodRequestBody(int patientID) {
            this.patientID = patientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DischargePatientWebMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DischargePatientWebMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponseBody Body;
        
        public DischargePatientWebMethodResponse() {
        }
        
        public DischargePatientWebMethodResponse(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DischargePatientWebMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] DischargePatientWebMethodResult;
        
        public DischargePatientWebMethodResponseBody() {
        }
        
        public DischargePatientWebMethodResponseBody(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] DischargePatientWebMethodResult) {
            this.DischargePatientWebMethodResult = DischargePatientWebMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RingAlarmWebMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RingAlarmWebMethod", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequestBody Body;
        
        public RingAlarmWebMethodRequest() {
        }
        
        public RingAlarmWebMethodRequest(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RingAlarmWebMethodRequestBody {
        
        public RingAlarmWebMethodRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RingAlarmWebMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RingAlarmWebMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponseBody Body;
        
        public RingAlarmWebMethodResponse() {
        }
        
        public RingAlarmWebMethodResponse(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RingAlarmWebMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.AlertFinalListStructure[] RingAlarmWebMethodResult;
        
        public RingAlarmWebMethodResponseBody() {
        }
        
        public RingAlarmWebMethodResponseBody(ICUPatientMonitorModuleLib.AlertWebServiceReference.AlertFinalListStructure[] RingAlarmWebMethodResult) {
            this.RingAlarmWebMethodResult = RingAlarmWebMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PatientDataWebMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PatientDataWebMethod", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequestBody Body;
        
        public PatientDataWebMethodRequest() {
        }
        
        public PatientDataWebMethodRequest(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PatientDataWebMethodRequestBody {
        
        public PatientDataWebMethodRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PatientDataWebMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PatientDataWebMethodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponseBody Body;
        
        public PatientDataWebMethodResponse() {
        }
        
        public PatientDataWebMethodResponse(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PatientDataWebMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] PatientDataWebMethodResult;
        
        public PatientDataWebMethodResponseBody() {
        }
        
        public PatientDataWebMethodResponseBody(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] PatientDataWebMethodResult) {
            this.PatientDataWebMethodResult = PatientDataWebMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICUPatientAlertServiceSoapChannel : ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CUPatientAlertServiceSoapClient : System.ServiceModel.ClientBase<ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap>, ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap {
        
        public CUPatientAlertServiceSoapClient() {
        }
        
        public CUPatientAlertServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CUPatientAlertServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUPatientAlertServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUPatientAlertServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.ConfigureBedsWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest request) {
            return base.Channel.ConfigureBedsWebMethod(request);
        }
        
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.BedData[] ConfigureBedsWebMethod(int numOfBeds) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequestBody();
            inValue.Body.numOfBeds = numOfBeds;
            ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse retVal = ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).ConfigureBedsWebMethod(inValue);
            return retVal.Body.ConfigureBedsWebMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse> ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.ConfigureBedsWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest request) {
            return base.Channel.ConfigureBedsWebMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodResponse> ConfigureBedsWebMethodAsync(int numOfBeds) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.ConfigureBedsWebMethodRequestBody();
            inValue.Body.numOfBeds = numOfBeds;
            return ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).ConfigureBedsWebMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.AllocateBedsWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest request) {
            return base.Channel.AllocateBedsWebMethod(request);
        }
        
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] AllocateBedsWebMethod(int patientID) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequestBody();
            inValue.Body.patientID = patientID;
            ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse retVal = ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).AllocateBedsWebMethod(inValue);
            return retVal.Body.AllocateBedsWebMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse> ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.AllocateBedsWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest request) {
            return base.Channel.AllocateBedsWebMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodResponse> AllocateBedsWebMethodAsync(int patientID) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.AllocateBedsWebMethodRequestBody();
            inValue.Body.patientID = patientID;
            return ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).AllocateBedsWebMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.DischargePatientWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest request) {
            return base.Channel.DischargePatientWebMethod(request);
        }
        
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] DischargePatientWebMethod(int patientID) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequestBody();
            inValue.Body.patientID = patientID;
            ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse retVal = ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).DischargePatientWebMethod(inValue);
            return retVal.Body.DischargePatientWebMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse> ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.DischargePatientWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest request) {
            return base.Channel.DischargePatientWebMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodResponse> DischargePatientWebMethodAsync(int patientID) {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.DischargePatientWebMethodRequestBody();
            inValue.Body.patientID = patientID;
            return ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).DischargePatientWebMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.RingAlarmWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest request) {
            return base.Channel.RingAlarmWebMethod(request);
        }
        
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.AlertFinalListStructure[] RingAlarmWebMethod() {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequestBody();
            ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse retVal = ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).RingAlarmWebMethod(inValue);
            return retVal.Body.RingAlarmWebMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse> ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.RingAlarmWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest request) {
            return base.Channel.RingAlarmWebMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodResponse> RingAlarmWebMethodAsync() {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.RingAlarmWebMethodRequestBody();
            return ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).RingAlarmWebMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.PatientDataWebMethod(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest request) {
            return base.Channel.PatientDataWebMethod(request);
        }
        
        public ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientInfo[] PatientDataWebMethod() {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequestBody();
            ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse retVal = ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).PatientDataWebMethod(inValue);
            return retVal.Body.PatientDataWebMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse> ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap.PatientDataWebMethodAsync(ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest request) {
            return base.Channel.PatientDataWebMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodResponse> PatientDataWebMethodAsync() {
            ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest inValue = new ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequest();
            inValue.Body = new ICUPatientMonitorModuleLib.AlertWebServiceReference.PatientDataWebMethodRequestBody();
            return ((ICUPatientMonitorModuleLib.AlertWebServiceReference.ICUPatientAlertServiceSoap)(this)).PatientDataWebMethodAsync(inValue);
        }
    }
}
